export const GET_ARTIST_LIST_ASYNC = 'GET_ARTIST_LIST_ASYNC';
export const GET_RECORD_LIST_ASYNC = 'GET_RECORD_LIST_ASYNC';
export const PUT_ARTIST_ASYNC = 'PUT_ARTIST_ASYNC';
export const PUT_RECORD_ASYNC = 'PUT_RECORD_ASYNC';
export const POST_ARTIST_ASYNC = 'POST_ARTIST_ASYNC';
export const POST_RECORD_ASYNC = 'POST_RECORD_ASYNC';

export const ADD_ARTIST = 'ADD_ARTIST';
export const ADD_RECORD = 'ADD_RECORD';
export const UPDATE_ARTIST = 'UPDATE_ARTIST';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const DELETE_ARTIST = 'DELETE_ARTIST';
export const DELETE_RECORD = 'DELETE_RECORD';

export const SET_SELECTED_ARTIST = 'SET_SELECTED_ARTIST';
export const SET_SELECTED_RECORD = 'SET_SELECTED_RECORD';

